CREATE TABLE service_frequencies (
    id INT AUTO_INCREMENT PRIMARY KEY,

    name VARCHAR(12) NOT NULL UNIQUE,
    days_interval SMALLINT UNSIGNED NOT NULL UNIQUE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	ON UPDATE CURRENT_TIMESTAMP 

);
